#!/bin/sh
ssh -t -t -o StrictHostKeyChecking=no root@bling.codes<<EOF
   cd /home/projects/node/ticket-backend
   git pull origin main
   npm install --production
   pm2 restart all npm --update-env
   exit
EOF
